name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo npm install

    - name: Build project
      run: sudo npm run build

    # - name: Change permission
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     port: ${{ secrets.SERVER_PORT }}
    #     script: |
    #       cd var/www/donprasetiyo.com && sudo chmod -R 777 .
    #       sudo rm -f html
    #       whoami
          
    - name: Transfer all files to Ubuntu Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "."
        target: "/var/www/donprasetiyo.com/html"
        overwrite: true
        rm: true
        command_timeout: 1000m

    - name: Restarting pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          pm2 stop process.json
          pm2 restart process.json

    # - name: Transfer build to Ubuntu Server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     port: ${{ secrets.SERVER_PORT }}
    #     source: ".next"
    #     target: "/var/www/donprasetiyo.com/html/.next"
    #     overwrite: true
    #     rm: true
    #     strip_components: 1
    #     command_timeout: 1000m

    # - name: Transfer node modules to Ubuntu Server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     port: ${{ secrets.SERVER_PORT }}
    #     source: "node_modules"
    #     target: "/var/www/donprasetiyo.com/html/node_modules"
    #     overwrite: true
    #     rm: true
    #     strip_components: 1
    #     command_timeout: 1000m